cookbook/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  
  root controller: 'home', action: 'index'

  get "/about", controller: "home", action: "about", as: "about"

  get "/contact", controller: "home", action: "contact", as: "contact"
  
  get "/admin", controller: "index", action: "index"

end

cookbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      session[:logged_in] = (user == 'admin' && password == 'password')
    end
    if user = authenticate_with_http_basic {|user_name, password| User.authenticate(user,
    password) }
      session[:user_id] = user.id
      session[:logged_in] = true
    else
      request_http_basic_authentication
    end
  end
  helper_method :logged_in?
  
  def logged_in?
    session[:logged_in]
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

cookbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @number_of_recipes = Recipe.count
  end
  def recipe
  end
  def contact
  end
end

cookbook/app/helpers/home_helper.rb
module HomeHelper
end

cookbook/app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

cookbook/app/views/home/contact.html.erb
<h2>Contact</h2>
<p>Contact us at home</p>

cookbook/app/views/home/index.html.erb
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>

cookbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Cookbook</title>
    <%= stylesheet_link_tag 'application',
     media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>  
  <body>
    <div class="container">
      <header>
        <h1>Our Cookbook</h1>
      </header>
      <section class="content">
        <nav>
         <%=link_to 'Home', root_url %> 
         <%=link_to 'Recipes', recipes_url %>
         <%=link_to 'Contact', contact_url %>
        </nav>
        <% if notice %>
          <div id="notice">
           <%= notice %>
          </div>
        <% end %>
        <%= yield %>
      </section>
      <footer>
        <h4>Copyright <%= Date.today.year %> OurCookbook</h4>
      </footer>
    </div>
  </body>
</html>